name: Generar APK con Permisos Reales
on:
  push:
    branches: [ "principal", "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar y Compilar Web
        run: |
          npm install
          npm run build

      - name: Crear APK Forzando Permisos de Red
        uses: jantzen/web-to-apk-action@v1
        with:
          input-dir: dist
          app-name: "Chatdanis"
          package-id: "com.danis.chatdanis"
          # Aquí obligamos a la herramienta a activar el internet
          permissions: "INTERNET, ACCESS_NETWORK_STATE"

      - name: Descargar APK Aqui
        uses: actions/upload-artifact@v4
        with:
          name: Chatdanis-Instalable
          path: "*.apk"
